sudo: required
services:
  - docker

before_install:
  - docker build -t thetalorian/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run thetalorian/react-test npm test -- --coverage

after_success:
  - docker build -t thetalorian/md-client ./client
  - docker build -t thetalorian/md-server ./server
  - docker build -t thetalorian/md-worker ./worker
  - docker build -t thetalorian/md-nginx ./nginx
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thetalorian/md-client
  - docker push thetalorian/md-server
  - docker push thetalorian/md-worker
  - docker push thetalorian/md-nginx

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-315066089897
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY